// sw.js — GENERATED by scripts/build-docs.py. Do not edit by hand.
// Cache name embeds a hash of every precached file; any content change
// produces a new name, so the old cache is dropped on activate.
const CACHE = 'dc-course-9d59d0afd3bf';
const PRECACHE = [
  "./APX-foundations.html",
  "./L3-foundations.html",
  "./fonts/IBMPlexMono-Regular.woff2",
  "./fonts/IBMPlexSans-Italic.woff2",
  "./fonts/IBMPlexSans-Medium.woff2",
  "./fonts/IBMPlexSans-Regular.woff2",
  "./fonts/IBMPlexSans-SemiBold.woff2",
  "./glossary.html",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./index.html",
  "./manifest.json",
  "./overview.html",
  "./site.css",
  "./site.js"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache:'reload' bypasses the HTTP cache so a new SW never precaches a
    // stale copy the browser was holding.
    await Promise.all(PRECACHE.map((url) =>
      cache.add(new Request(url, { cache: 'reload' }))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((n) => n.startsWith('dc-course-') && n !== CACHE)
      .map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

const scopeUrl = new URL(self.registration.scope);

function isHtml(request) {
  if (request.mode === 'navigate') return true;
  const accept = request.headers.get('accept') || '';
  return accept.includes('text/html') || request.url.endsWith('.html');
}

// Directory requests (".../learn-datacenter-epc/") map to index.html.
function cacheKey(request) {
  const url = new URL(request.url);
  if (url.pathname.endsWith('/')) url.pathname += 'index.html';
  url.search = '';
  url.hash = '';
  return url.href;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== scopeUrl.origin) return;
  if (!url.pathname.startsWith(scopeUrl.pathname)) return;

  if (isHtml(request)) {
    // Network-first: a fresh wrap is picked up when online; offline falls
    // back to the cached page, then to the index as a last resort.
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        const fresh = await fetch(request);
        if (fresh && fresh.ok) cache.put(cacheKey(request), fresh.clone());
        return fresh;
      } catch (err) {
        const cached = await cache.match(cacheKey(request));
        if (cached) return cached;
        const index = await cache.match(new URL('./index.html', scopeUrl).href);
        if (index) return index;
        return new Response('Offline and this page is not cached yet.',
          { status: 503, headers: { 'Content-Type': 'text/plain' } });
      }
    })());
    return;
  }

  // Everything else (icons, manifest): cache-first, fill cache on miss.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(cacheKey(request));
    if (cached) return cached;
    const fresh = await fetch(request);
    if (fresh && fresh.ok) cache.put(cacheKey(request), fresh.clone());
    return fresh;
  })());
});
