// sw.js — GENERATED by scripts/build-docs.py. Do not edit by hand.
// Cache name embeds a hash of every precached file; any content change
// produces a new name, so the old cache is dropped on activate.
const CACHE = 'dc-course-70df9c34b247';
const PRECACHE = [
  "./APX-building.html",
  "./APX-commissioning.html",
  "./APX-compute.html",
  "./APX-cooling.html",
  "./APX-foundations.html",
  "./APX-network.html",
  "./APX-power-1.html",
  "./APX-power-2.html",
  "./APX-requirements.html",
  "./APX-security-monitoring.html",
  "./APX-site.html",
  "./L3-building.html",
  "./L3-commissioning.html",
  "./L3-compute.html",
  "./L3-cooling.html",
  "./L3-foundations.html",
  "./L3-network.html",
  "./L3-power-1.html",
  "./L3-power-2.html",
  "./L3-requirements.html",
  "./L3-security-monitoring.html",
  "./L3-site.html",
  "./figures/building/hall1-exploded.png",
  "./figures/building/rigging-path.png",
  "./figures/building/white-space-section.png",
  "./figures/commissioning/handover-table.png",
  "./figures/commissioning/itad-chain-of-custody.png",
  "./figures/commissioning/nightshift-mop.png",
  "./figures/commissioning/pull-the-plug-day.png",
  "./figures/compute/ai-pod-room.png",
  "./figures/compute/nvl72-exploded.png",
  "./figures/compute/rack-arrives-loaded.png",
  "./figures/compute/three-racks.png",
  "./figures/cooling/ai-pod-cutaway.png",
  "./figures/cooling/chip-to-sky.png",
  "./figures/cooling/containment-and-fan-wall.png",
  "./figures/cooling/plant-yard-and-roof.png",
  "./figures/foundations/campus-site-plan.png",
  "./figures/foundations/hall-cutaway.png",
  "./figures/network/ai-pod-rail-fabric.png",
  "./figures/network/hall1-cabling-rooms.png",
  "./figures/network/meet-me-room.png",
  "./figures/network/overhead-section.png",
  "./figures/power-1/chain-cutaway.png",
  "./figures/power-1/first-thirty-seconds.png",
  "./figures/power-1/generator-yard.png",
  "./figures/power-1/inside-a-block.png",
  "./figures/power-2/3m2-rooms-and-paths.png",
  "./figures/power-2/ai-pod-overhead.png",
  "./figures/power-2/rack-rear-ac-vs-orv3.png",
  "./figures/requirements/day-one-section.png",
  "./figures/requirements/tier3-vs-tier4.png",
  "./figures/requirements/two-racks-same-footprint.png",
  "./figures/requirements/white-space-plan.png",
  "./figures/security-monitoring/battery-room.png",
  "./figures/security-monitoring/zones-plan.png",
  "./figures/site/bridge-beside-dark-substation.png",
  "./figures/site/site-constraints-plan.png",
  "./figures/site/substation-scope.png",
  "./fonts/IBMPlexMono-Regular.woff2",
  "./fonts/IBMPlexSans-Italic.woff2",
  "./fonts/IBMPlexSans-Medium.woff2",
  "./fonts/IBMPlexSans-Regular.woff2",
  "./fonts/IBMPlexSans-SemiBold.woff2",
  "./glossary.html",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./index.html",
  "./manifest.json",
  "./overview.html",
  "./site.css",
  "./site.js"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache:'reload' bypasses the HTTP cache so a new SW never precaches a
    // stale copy the browser was holding.
    await Promise.all(PRECACHE.map((url) =>
      cache.add(new Request(url, { cache: 'reload' }))));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((n) => n.startsWith('dc-course-') && n !== CACHE)
      .map((n) => caches.delete(n)));
    await self.clients.claim();
  })());
});

const scopeUrl = new URL(self.registration.scope);

function isHtml(request) {
  if (request.mode === 'navigate') return true;
  const accept = request.headers.get('accept') || '';
  return accept.includes('text/html') || request.url.endsWith('.html');
}

// Directory requests (".../learn-datacenter-epc/") map to index.html.
function cacheKey(request) {
  const url = new URL(request.url);
  if (url.pathname.endsWith('/')) url.pathname += 'index.html';
  url.search = '';
  url.hash = '';
  return url.href;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== scopeUrl.origin) return;
  if (!url.pathname.startsWith(scopeUrl.pathname)) return;

  if (isHtml(request)) {
    // Network-first: a fresh wrap is picked up when online; offline falls
    // back to the cached page, then to the index as a last resort.
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      try {
        const fresh = await fetch(request);
        if (fresh && fresh.ok) cache.put(cacheKey(request), fresh.clone());
        return fresh;
      } catch (err) {
        const cached = await cache.match(cacheKey(request));
        if (cached) return cached;
        const index = await cache.match(new URL('./index.html', scopeUrl).href);
        if (index) return index;
        return new Response('Offline and this page is not cached yet.',
          { status: 503, headers: { 'Content-Type': 'text/plain' } });
      }
    })());
    return;
  }

  // Everything else (icons, manifest): cache-first, fill cache on miss.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(cacheKey(request));
    if (cached) return cached;
    const fresh = await fetch(request);
    if (fresh && fresh.ok) cache.put(cacheKey(request), fresh.clone());
    return fresh;
  })());
});
